import Modal from "../../components/common/Modal";

function ReportModal({

    showModal,

    setShowModal,

    formData,

    setFormData,

    handleSave,

    editingId

}) {

    if (!showModal) return null;

    return (

        <Modal
            title={editingId ? "Edit Report" : "Add Report"}
            onClose={() => setShowModal(false)}
        >

            <input
                placeholder="Report ID"
                value={formData.reportId}
                onChange={(e) =>
                    setFormData({
                        ...formData,
                        reportId: e.target.value
                    })
                }
            />

            <input
                placeholder="Report Name"
                value={formData.reportName}
                onChange={(e) =>
                    setFormData({
                        ...formData,
                        reportName: e.target.value
                    })
                }
            />

            <input
                placeholder="Category"
                value={formData.category}
                onChange={(e) =>
                    setFormData({
                        ...formData,
                        category: e.target.value
                    })
                }
            />

            <input
                placeholder="Generated By"
                value={formData.generatedBy}
                onChange={(e) =>
                    setFormData({
                        ...formData,
                        generatedBy: e.target.value
                    })
                }
            />

            <select
                value={formData.status}
                onChange={(e) =>
                    setFormData({
                        ...formData,
                        status: e.target.value
                    })
                }
            >

                <option>Generated</option>
                <option>Pending</option>
                <option>Archived</option>

            </select>

            <button onClick={handleSave}>

                {

                    editingId

                        ? "Update Report"

                        : "Save Report"

                }

            </button>

        </Modal>

    );

}

export default ReportModal;