function ReportTable({
    reports,
    handleEdit,
    handleDelete
}) {
    return (
        <>
            <h2 className="table-title">
                Report List
            </h2>

            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Report Name</th>
                        <th>Generated By</th>
                        <th>Budget</th>
                        <th>Category</th>
                        <th>Created Date</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody>
                    {reports.length === 0 ? (
                        <tr>
                            <td colSpan="8">
                                No Reports Found
                            </td>
                        </tr>
                    ) : (
                        reports.map((report) => (
                            <tr key={report._id}>
                                <td>{report.reportId}</td>
                                <td>{report.reportName}</td>
                                <td>{report.generatedBy}</td>
                                <td>₹{report.budget}</td>
                                <td>{report.category}</td>
                                <td>
                                    {new Date(report.createdDate).toLocaleDateString()}
                                </td>
                                <td>
                                    <span
                                        className={
                                            report.status === "Completed"
                                                ? "status completed"
                                                : report.status === "In Progress"
                                                ? "status progress"
                                                : "status pending"
                                        }
                                    >
                                        {report.status}
                                    </span>
                                </td>
                                <td>
                                    <button
                                        className="edit-btn"
                                        onClick={() => handleEdit(report)}
                                    >
                                        Edit
                                    </button>

                                    <button
                                        className="delete-btn"
                                        onClick={() => handleDelete(report._id)}
                                    >
                                        Delete
                                    </button>
                                </td>
                            </tr>
                        ))
                    )}
                </tbody>
            </table>
        </>
    );
}

export default ReportTable;