function ReportTable({

    reports,

    handleEdit,

    handleDelete

}) {

    return (

        <>

            <h2 className="table-title">

                Reports

            </h2>

            <table>

                <thead>

                    <tr>

                        <th>ID</th>
                        <th>Report Name</th>
                        <th>Category</th>
                        <th>Generated By</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>Action</th>

                    </tr>

                </thead>

                <tbody>

                    {

                        reports.length === 0 ?

                        (

                            <tr>

                                <td colSpan="7">

                                    No Reports Found

                                </td>

                            </tr>

                        )

                        :

                        reports.map((report) => (

                            <tr key={report._id}>

                                <td>{report.reportId}</td>

                                <td>{report.reportName}</td>

                                <td>{report.category}</td>

                                <td>{report.generatedBy}</td>

                                <td>

                                    {

                                        new Date(

                                            report.createdDate

                                        ).toLocaleDateString()

                                    }

                                </td>

                                <td>

                                    <span
                                        className={`status ${report.status.toLowerCase()}`}
                                    >

                                        {report.status}

                                    </span>

                                </td>

                                <td>

                                    <button
                                        className="edit-btn"
                                        onClick={() =>
                                            handleEdit(report)
                                        }
                                    >

                                        Edit

                                    </button>

                                    <button
                                        className="delete-btn"
                                        onClick={() =>
                                            handleDelete(report._id)
                                        }
                                    >

                                        Delete

                                    </button>

                                </td>

                            </tr>

                        ))

                    }

                </tbody>

            </table>

        </>

    );

}

export default ReportTable;